# Generated by Django 4.2.2 on 2023-06-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="answers",
        ),
        migrations.AddField(
            model_name="answer",
            name="from_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="activities.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_answers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="question", to="activities.answer"
            ),
        ),
    ]
